# -*- coding: utf-8 -*-
"""control_state.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EKvJBbNttMAeyxtkBMIb0vLhoi3jczE

#Control staments - if-else
"""

age=36
gender="Female"
if age>=18 and gender=="Female":
    print("Entry Freee")

"""#if else ladder (if-elif-else)"""

#Validating input
age=55
time =20

if type(age)!=int and age==0:
    print("Invalid age")
elif age<=18:
    print("under age")
elif age>=50:
    print("Over Age")
else: print("allowed")

#first if statement is checked , age is less than 18 check and age is greater than check
#which block is true that statement will get executed
#in above code we can clearly see that age is 55 which is greater than 50 so will get over age in output

"""#Nested if- else"""

#finding largest number among three
a=10
b=13
c=18

if a>=b: #if a is bigger it will check next if else go to the else block
    if a>=c:
        print("largest", a)
    else:
        print("largest",c)
else:
    if b>=c:
        print("largest",b)
    else:
        print("largest",c)

"""#2. For Loops"""

grades = [98, 76, 77, 81, 100, 96, 69, 75, 83, 83]
total=0
count=0
for marks in grades:
    count+=1
    if marks>100:
        print("ivalid marks")
        continue
    total+=marks
print("total grade=", total)

# calculating average
average= total/count

print(average)

principal_amount=float(input())

interest_rate=float(input())

time_in_year=float(input())

print("principal amount: ",principal_amount)
print("interest_rate: ",interest_rate)
print("time_in_year: ",time_in_year)

simple_interest=(principal_amount*interest_rate*time_in_year)/100
print(simple_interest)
total_returnable_amt=principal_amount+simple_interest
print("total_returnable_amt: ",total_returnable_amt)

"""#3.While Loop"""

grades = [98, 76, 77, 81, 100, 96, 69, 75, 83, 83]
grade_counter = 1
total = 0  # initialize total

while grade_counter <= len(grades):
    grade = grades[grade_counter - 1]

    if grade >= 100:
        print("Invalid Grades!! at", grade_counter)
        grade_counter += 1   # increment here too to avoid infinite loop
        continue
    else:
        total += grade

    grade_counter += 1   # increment counter after processing each grade

print("Average is", round(total / len(grades)))

"""#4. List Comprehensions"""

marks=[90,34,38,24,49]
fail=[mark for mark in marks if mark < 35]
print(fail)

marks = [90, 89, 56, 67, 29, 49]
fail = [mark for mark in marks if mark < 35]
print(fail)

"""#5. Dictionary Iteration

"""

my_dict = {
    'B1': {'Topic': 'Python', 'Status': 'Ongoing', 'students': ['Vinay', 'Deepika', 'Gaurav']},
    'B2': {'Topic': 'R', 'Status': 'Ongoing', 'students': ['Deepika', 'Gaurav', 'Manish']}
}

students=[]
for batch_id, batch_details in my_dict.items():
    if batch_details['Status']=='Ongoing':
        students.append(batch_details['students'])
print(set(students[0]).intersection(set(students[1])))

