# -*- coding: utf-8 -*-
"""datatype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15bUn1VseR_1mHtyG5pKv_Lgc52ghqB0l

#Data Types in Python

Primitive Data types
"""

#integer:
i=10
print(i)

i+=2 # shortcut of i=i+2
print(i) # i=12
print(i+2) #12+2=14
print(i*2)# 12*2=24
print(i/2)#12/2=6
print(i%2) #12%2=0 reminder
print(i//2)# floor division (quotient will be rounded off)
print(i**2)# i^2=144

#Floats
f=1.618
print(f)
print(f+2)

#Booleans

b=True
print(b)
print(not b) # not compliments the b from true to false

a,b=3,6
print(a,b)

print(a<b)

print(a!=b)

print(a>=b)

print(not a)

#String
s1="hello"
s2="world"
s3="2018"
print(s1)
print(s2)
print(s3)

print(s1.isdigit())# to chekc s1 is digit- false
print(s2.upper())# output- WORLD
print(s3.isdigit()) #output-true

s4="few words are not repeated, few words are"
print(s4)
print(s4.split())# splits string into a list

"""Non- Primitive Data Types"""

#Lists :- lists are ordered collection of data elements.
#it is mutable- means we can modify the list by adding or deleting the list elements

fruits=['Apple', 'Mango', 'Banana', 'Chiku']
print(fruits)
fruits.append('kivi') # appending sigle element at the end of the list
print(fruits)
fruits.append(['Pineapple','Watermelon'])# we can append a list inside a list
print(fruits)

#Accessing list element(indexing)
print(fruits[1:3]) #output ['Mango', 'Banana']
print(fruits[:3]) # output ['Apple', 'Mango','Banana' ]
print(fruits[1:]) #output ['Mango', 'Banana', 'Chiku','kivi', ['Pineapple', 'Watermelon']]

#Tuples: Tuples are ordered collection of data elements
#these are immutable- we cannot modify the tuple by adding or deleting elements

t1=(2,4,6,4,8,5,9)
t2=(0,2,1)
print(t1+t2) #output -(2,4,6,4,8,5,9,0,2,1)
print(t1[4]) #output- 8
print(t1[1:4]) #output - (4,6,4)
#print(t2[2]=5)- Error because tuples are immutable

#Dictionaries: dictionary data type contains information in key value pair
#Values of a dictionary can be changed but key's value cannot be changed

dict1={
    "S": "Supervised",
    "US": "Unsupervised",
    "fruits":['Mango', 'Banana'],
    3: {"a": "ABC", "b": "PQR"}
}
print(dict1)

print(dict1["fruits"])

dict1["S"]="Stable"
print(dict1)

from collections import defaultdict
repeated_word_count = defaultdict(int)
s4 = "Few words are not repeated, few words are"
for word in s4.split():
    repeated_word_count[word] += 1
print(repeated_word_count)

#Sets: Sets are collection of unique elemnts

str1="few words are not repeated, few words are"
str2= "Golden words are not repeated"
set1= set(str1.split())
set2=set(str2.split())
print(set1)
print(set2)
print(set1.union(set2))
print(set1.intersection(set2))



