# -*- coding: utf-8 -*-
"""Function&Exception.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUtruzLaCYuw3aRoPCT9PaRlkCNqaVWX

#Function with default arguments
"""

def add(n1=1, n2=7):
    return n1+n2
print(add())#none argument is passed

print(add(2)) #since only one argument is passed this will assigned to 1st argument

print(add(3,8))#both arguments are passed

"""#Function without returen statement

"""

def addition(num1, num2):
    sum=num1+num2
    print(sum)

addition(3,4)

print(addition(2,4))

type(addition)

ret=addition(5,6)
print(ret)

# Less flexible
def square_and_print(x):
    print(x * x)

# More flexible
def square(x):
    return x * x

print(square(5))        # can print
area = square(5) * 3.14 # can reuse in another calculation

"""#Variable argument (*arg)"""

def arithmetic_mean(x, *l):
    sum = x
    for i in l:
        sum += i
    return sum / (1.0 + len(l))
l = [23, 34, 56, 75, 78, 49, 6]
print(arithmetic_mean(10, *l))

def details(**data):
    for k, v in data.items():
        print(f"{k} = {v}")
details(Name="Sejal", LastName="Yadav")  # Name = Vinay, LastName = Borhade

from functools import partial

def power(base, exponent):
    return base ** exponent

# Create a new function with exponent fixed to 2
square = partial(power, exponent=2)

print(square(5))  # 5^2 = 25
print(square(8))  # 8^2 = 64

def recurse(k):
    if k > 0:
        result = k + recurse(k - 1)
        print(result)
    else:
        result = 0
    return result
recurse(3)

l = [12, 14, 13, 56, "vinay", "14"]
div = 0
try:
    for i in l:
        print(i / div)
except ZeroDivisionError:
    print("you cannot divide by zero")
except TypeError:
    print("input should be a number")

class MyError(Exception):
    pass
def divide(x, y):
    try:
        if x == 0 and y == 0:
            raise MyError
        result = x / y
        print("result is", result)
    except MyError:
        print("Are you nuts!")
    except ZeroDivisionError:
        print("**Invalid Denom** - division by zero!")
    finally:
        print("executing finally clause")
divide(0, 0)

